### ISSUE TITLE
关于CARPK数据集微调部分

### ISSUE THREAD

**Issue by xuebaobizui1** [Verg-Avesta/CounTR#11]
在Finetune on CARPK部分，我发现训练速度非常的缓慢，大约一小时2个epoch，按照这个速度在3090上需要训练几十天，这显然是不正常的。与此同时内存的占用很高，但是显存的占用很低。
我尝试修改num_workers的数值以及batch size的大小，发现会因为输入形状问题报错。不知道这是否是因为使用了deeplake的缘故。
或许应该在本地CARPK上进行训练？如果在本地训练的话，我该怎么修改FSC_finetune_CARPK.py，或许您能给我一些建议！！感激不尽！！！

**Comment by Verg-Avesta** [comment]
当时我在Finetune on CARPK时，确实由于hub提供的服务不稳定，有时会断联，所以时不时有些图片的load可能会需要比较长的时间，但也不至于到了一个小时2个epoch这么夸张的地步，并且没有出现内存占用高而显存占用低的问题。我不确定你是否把device设置成CPU了？如果不是的话，那可能就是服务器网络的问题。

如果你们服务器确实不能很好地使用hub的服务的话，你也可以在[这里](https://drive.google.com/file/d/0BwSzgS8Mm48Ud2h2dW40Wko3a1E/view?resourcekey=0-34K_uP-vYM7EWq0Q2iIVaw)下载CARPK数据集。然后主要是要把FSC_finetune_CARPK.py 中的[line 204](https://github.com/Verg-Avesta/CounTR/blob/4fa1aa440ca1906c2f1c5ce54e0465ce954b8bb3/FSC_finetune_CARPK.py#L204)到[line 240](https://github.com/Verg-Avesta/CounTR/blob/4fa1aa440ca1906c2f1c5ce54e0465ce954b8bb3/FSC_finetune_CARPK.py#L240)这部分数据预处理模仿FSC_finetune_cross.py中[line 122](https://github.com/Verg-Avesta/CounTR/blob/4fa1aa440ca1906c2f1c5ce54e0465ce954b8bb3/FSC_finetune_cross.py#L122)对FSC147做的那样，改写一下。剩下的可能就是要改一下[line 261](https://github.com/Verg-Avesta/CounTR/blob/4fa1aa440ca1906c2f1c5ce54e0465ce954b8bb3/FSC_finetune_CARPK.py#L261)这里关于gt的部分。我当时没有在本地CARPK上训练，所以可能没法提出很具体的建议，希望我上面说的这些能帮到你。

**Comment by xuebaobizui1** [comment]
非常感谢！！！这对我很有帮助
