### ISSUE TITLE
Counting Multiple object class

### ISSUE THREAD

**Issue by jaideep11061982** [Verg-Avesta/CounTR#13]
If I have got objects having different shapes,sizes and colors then do I need exemplar bounding box for each different type of object varrying in shapes/sizes/colors  to count
Say I have total 40 objects  , 8 Different type of objects having 5 instances each.
Do I need min 8 exampler boxes  or  it can be less object type 
@WeidiXie @Verg-Avesta

**Comment by Verg-Avesta** [comment]
The model has generalization ability and is robust to small differences in color, shape, and size.  Therefore, it is only needed to select a few representative exemplars for counting. 

In fact, objects are generally not considered to belong to the same category when their shapes differ greatly.  If you want to count objects with great shape difference, it is better to count them as different categories and each time count one category.

**Comment by jaideep11061982** [comment]
@Verg-Avesta thanku for quick response.
During inference how can one get the exemplar bounding box. In your demo you have hard coded it for the image. But in real world how those bounding boxes can be generated and passed to the model

**Comment by Verg-Avesta** [comment]
In real world, the user should also draw several bound boxes in the image to clarify which category the user wants to count. This is what have to be done by the users because if there are multiple classes of objects, no one will know which class to count except the user.
