### ISSUE TITLE
Results of zero-shot counting

### ISSUE THREAD

**Issue by Elin24** [Verg-Avesta/CounTR#20]
In your paper, Table.1 presents the results of zero-shot counting:
> ![image](https://user-images.githubusercontent.com/22393807/213909375-4c9d5a2e-0ac0-4c66-8a55-92056388982c.png)

However, this is different from Table.2:
> ![image](https://user-images.githubusercontent.com/22393807/213909382-4d3eb06e-04fe-4ca2-a1ef-f738a350c8c1.png)

So which is the right results?

**Comment by Verg-Avesta** [comment]
Sorry I just realized that I made a severe problem. The reuslt of Table.2 is correct, i.e. the correct performance of CounTR in zero-shot should be D0, not D1.

I will fix this problem in a new arxiv version of the paper. Thanks for pointing this problem out.

**Comment by Elin24** [comment]
Thanks for your reply.
