### ISSUE TITLE
List index out of range while resizeing

### ISSUE THREAD

**Issue by NateshReddy** [Verg-Avesta/CounTR#22]
![image](https://user-images.githubusercontent.com/47558025/215351887-909d8786-9376-4d59-8388-f236589dd7e5.png)

Getting this resize issue while finetuning with FSC_finetune_cross.py on my custom dataset. Can you please help me with this?

**Comment by Verg-Avesta** [comment]
The mosaic augmentation in FSC147.py needs the image to be 384x384, so maybe there is something wrong with the image size?
