### ISSUE TITLE
Question about the pretrained weight

### ISSUE THREAD

**Issue by donggoing** [Verg-Avesta/CounTR#3]
Hello, may I ask whether the pre-trained weight you provide refer to MAE pre-training weight on FSC-147/CARPK or the results after finetune?

**Comment by Verg-Avesta** [comment]
Hello.
It’s the fine-tuned model weights on FSC147 and CARPK. I have renamed it to avoid ambiguity.

**Comment by donggoing** [comment]
> Hello. It’s the fine-tuned model weights on FSC147 and CARPK. I have renamed it to avoid ambiguity.

Could you please provide the MAE(MIM) pre-trained weight on FSC-147/CARPK  to reproduce the result?

**Comment by Verg-Avesta** [comment]
I have just uploaded the pre-trained weights and you can download it from [here](https://drive.google.com/file/d/1ObuBkjt-p8-DUmQKXV3CxeEJ_MlU5RH8/view?usp=sharing).
