### ISSUE TITLE
What is the actual difference between the zero-shot and the few-shot test scripts?

### ISSUE THREAD

**Issue by JavierUrenaPhDProjects** [Verg-Avesta/CounTR#30]
Just that, what is the exact difference? I know zero-shot takes longer than few-shot, but I dont know exactly well what is the objective of one or the other.

**Comment by Verg-Avesta** [comment]
You can refer to the paper. Zero-shot uses zero exemplar bound boxes in counting, and some test-time normalisation tricks are corrsspondingly changed.
