### ISSUE TITLE
Demo with ONNX

### ISSUE THREAD

**Issue by tamnguyenvan** [Verg-Avesta/CounTR#33]
Hello,
Great work. This isn't exactly an issue. I have converted the FSC147.pth model to ONNX format and create a library that makes it easier for users to use it. I'm not sure if you can add my repo to the readme?

https://github.com/tamnguyenvan/vision-counter

Thanks,

**Comment by Verg-Avesta** [comment]
Hello,

Thank you for your great contribution to this project! It was incredibly helpful and I truly appreciate it. I have added your repo to the readme file. 

Thanks again!
