### ISSUE TITLE
Without Pretraining

### ISSUE THREAD

**Issue by Haalum** [Verg-Avesta/CounTR#37]
1. I am just curious how the model performs without doing any pertaining. I only want to train the model on FSC147 data. I commented out the following line in ```FSC_finetune_cross.py```.
```misc.load_model_FSC(args=args, model_without_ddp=model_without_ddp)```

Am I missing anything? 

2. Since I'm not fine-tuning, only training on FSC147 data. Any idea, what should be my epoch number to get an optimal result?

Thanks!

**Comment by Verg-Avesta** [comment]
As FSC-147 is a quite small dataset, it will be hard to train a good feature extractor without any kind of pre-training. 

But if you want to try it, you should also remove this [line](https://github.com/Verg-Avesta/CounTR/blob/3b37a5502d1892a06470d2523daab489f03b8840/models_mae_cross.py#L204C21-L204C21) which freezes the image encoder, besides what you have done.

For the epoches, maybe the larger the better? But I am not quite sure whether it will work.

**Comment by Haalum** [comment]
I understand. I'm just curious. Thank you.
