### ISSUE TITLE
question about density map

### ISSUE THREAD

**Issue by zhitao654321** [Verg-Avesta/CounTR#38]
Hello. Thank you for the great work.
I got curious. Why did you choose to mark dots on the ground truth density map,  instead of using original density map with Gaussian distribution from FSC147 dataset ? Just wondering about your thoughts on this. Thanks

**Comment by Verg-Avesta** [comment]
Hello. Thanks for your attention.

In the original density map of FSC-147, the writers used an adaptive window size for Gaussian smoothing, which means different objects have different size of annotations. Thus, the model have to learn object size information besides counting. To remove the effect of different object size, we re-generate the Gaussian density map with a fixed window size based on the point-annotations.

**Comment by zhitao654321** [comment]
I get it, thank you very much
