### ISSUE TITLE
Could please upload pre-trained weight?

### ISSUE THREAD

**Issue by donggoing** [Verg-Avesta/CounTR#4]
Hello.It’s the fine-tuned model weights on FSC147 and CARPK. I have renamed it to avoid ambiguity.
_Originally posted by @Verg-Avesta in https://github.com/Verg-Avesta/CounTR/issues/3#issuecomment-1288566814_
      
Could you please provide the MAE(MIM) pre-trained weight on FSC-147/CARPK to reproduce the result? Please!

**Comment by Verg-Avesta** [comment]
Yes.
 I have just uploaded the pre-trained weights and you can download it from [here](https://drive.google.com/file/d/1ObuBkjt-p8-DUmQKXV3CxeEJ_MlU5RH8/view?usp=sharing).

**Comment by donggoing** [comment]
Thanks a lot! 
I would like to know which dataset this uploaded file was pre-trained on. @Verg-Avesta

**Comment by Verg-Avesta** [comment]
It‘s pre-trained by MAE on FSC147.
