### ISSUE TITLE
pytorch version issue

### ISSUE THREAD

**Issue by MelodyyyYin** [Verg-Avesta/CounTR#44]
<img width="554" alt="Screenshot 2024-04-21 at 1 23 40 PM" src="https://github.com/Verg-Avesta/CounTR/assets/97646140/aee6e0c5-6098-422f-8be4-fdf0ea4b68aa">

I have a version issue when downloading the suggested version of torch and torch version. Which version should I download?

<img width="627" alt="Screenshot 2024-04-21 at 1 29 27 PM" src="https://github.com/Verg-Avesta/CounTR/assets/97646140/53132e11-352d-4f39-b395-9ab18c54e90e">

I am not sure if this information is helpful.

**Comment by Verg-Avesta** [comment]
The environment I provided is suitable for RTX3090. If you are using TITAN with a higher CUDA version, please use a higher version of pytorch correspondingly.
