### ISSUE TITLE
Dataset images

### ISSUE THREAD

**Issue by jaideep11061982** [Verg-Avesta/CounTR#8]
1) Which dataset images & model
 we should use to run demo.py
I was trying out with fsc147 but dataset has got density map images not the raw jpg images

2) I am unable to find the annotations file 'annotation_FSC147_384.json' . 
Why do we need bounding boxes  out here. Could you help understand

**Comment by jaideep11061982** [comment]
@Verg-Avesta @WeidiXie

**Comment by Verg-Avesta** [comment]
1. I think you only donwloaded the density map, not the raw images. See [this](https://github.com/cvlab-stonybrook/LearningToCountEverything).
Model: Depends on the dataset you used, or directly use the model fine-tuned on FSC147.

2. Download it from [here](https://github.com/cvlab-stonybrook/LearningToCountEverything/tree/master/data).
Bound box: To use the exemplars, you obviously need their bound boxes. Please read the paper for more details.
