### ISSUE TITLE
Understanding PreTrain

### ISSUE THREAD

**Issue by jaideep11061982** [Verg-Avesta/CounTR#9]
@Verg-Avesta 
Could you help understand the versions of pretain

<html>
<body>

Pretrain on FSC147 | models_mae_noct.py | FSC_pretrain.py
-- | -- | --
Finetune on FSC147 | models_mae_cross.py | FSC_finetune_cross.py
Finetune on CARPK | models_mae_cross.py | FSC_finetune_CARPK.py

</body>
</html>

What is difference between these files, Pretrain, finetunecross and finetune CARPK

**Comment by Verg-Avesta** [comment]
FSC_pretrain.py is used to pretrain the model on FSC147.
FSC_finetune_cross.py is used to fine-tune the model on FSC147.
FSC_finetune_CARPK.py is used to finetune the model on CARPK.
Please read the paper for more details.
